"""Constants for the temperature monitoring system."""

# HTTP Status Codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_INTERNAL_SERVER_ERROR = 500

# HTTP Status Code Names (for readability)
STATUS_OK = HTTP_OK
STATUS_CREATED = HTTP_CREATED
STATUS_BAD_REQUEST = HTTP_BAD_REQUEST
STATUS_UNAUTHORIZED = HTTP_UNAUTHORIZED
STATUS_FORBIDDEN = HTTP_FORBIDDEN
STATUS_NOT_FOUND = HTTP_NOT_FOUND
STATUS_UNPROCESSABLE_ENTITY = HTTP_UNPROCESSABLE_ENTITY
STATUS_INTERNAL_SERVER_ERROR = HTTP_INTERNAL_SERVER_ERROR

